trigger:
- master

resources:
  repositories:
    - repository: pipelineTemplateRepository
      type: github
      name: icraftsoftware/Be.Stateless.Build.Agent.Yaml.Pipeline.Templates
      endpoint: github.com_icraftsoftware

extends:
    template: Templates/continuous-integration.yml@pipelineTemplateRepository
    parameters:
        ProjectOrSolutionPath: '$(Build.SourcesDirectory)/Be.Stateless.Stream.sln'
        Major: 2
        Minor: 0
